#-------Info-------#
VERSION: "v1.7"
DESCRIPTION: "First 5s with 21-22-23-24"
DATA_PATH: "inputs"
#################################################


#-------Global-------#
LOAD_SPEC_DATA: ["data/spec_first_5sec_256_256_24.npy",
                "data/spec_first_5sec_256_256_212223.npy"]
SEED: 24
#################################################


#-------Spectogram Transform-------#
SAMPLE_RATE: 32000
N_FFT: 1095 #[1024, 2048]
WIN_SIZE: 412
WIN_LAP: 100
MIN_FREQ: 40 #[20,50]
MAX_FREQ: 15000 #[14000,16000]
#################################################


#-------Mel Spectogram Transform-------#
N_FFT: 1024 #[1024, 2048]
N_MEL: 128
HOP_LENGTH: 320
WIN_SIZE: 412
WIN_LAP: 100
MIN_FREQ: 40 #[20,50]
MAX_FREQ: 15000 #[14000,16000]
#################################################

#-------Spectogram Augmentation-------#
XYMasking: True
#################################################


#-------Training hyperparameter-------#
EPOCHS: 10 #[5,30]
FOLD: 5
BACTHSIZE: 16
LABEL_SMOOTHING: 0.
#################################################