VERSION: "v0.7"
DATA_PATH: "inputs"
LOAD_SPEC_DATA: True

SEED: 24

SAMPLE_RATE: 32000
N_FFT: 1095
WIN_SIZE: 412
WIN_LAP: 100
MIN_FREQ: 40
MAX_FREQ: 15000

EPOCHS: 10
FOLD: 5
BACTHSIZE: 16
LABEL_SMOOTHING: 0.1