#-------Info-------#
VERSION: "v3.6"
DESCRIPTION: "top 5 google with stride 1s"
DATA_PATH: "inputs"
#################################################


#-------Global-------#
LOAD_SPEC_DATA: ["data/melspec_googletop5_256_256_24_wide.npy"]
IMAGE_SIZE: 256
SEED: 24
SECOND_LABEL: 1
SAMPLE_RATE: 32000
MIN_FREQ: 20 #[20,50]
MAX_FREQ: 16000 #[14000,16000]
N_FFT: 2048 #[1024, 2048]
#################################################


#-------Spectogram Transform-------#
WIN_SIZE: 412
WIN_LAP: 100
#################################################


#-------Mel Spectogram Transform-------
N_MEL: 128
HOP_LENGTH: 512
NORMALIZED: True
CENTER: True
PAD_MODE: "constant"
NORM: "slaney"
MEL_SCALE: "slaney"
#################################################

#-------Spectogram Augmentation-------#
XYMasking: True
CoarseDropout: True
HorizontalFlip: True
MixUp: True
#################################################


#-------Training hyperparameter-------#
BACKBONE: "tf_efficientnet_b0.in1k"
EPOCHS: 10 #[5,30]
FOLD: 5
BACTHSIZE: 48
LABEL_SMOOTHING: 0.
LOSS: FocalLoss #CrossEntropyLoss
#################################################