#-------Info-------#
VERSION: "v5.3"
DESCRIPTION: "Add DropOut"
DATA_PATH: "inputs"
#################################################


#-------Global-------#
LOAD_SPEC_DATA: ["data/melspec_googletop5_256_256_24_wide.npy"]
IMAGE_SIZE: 256
SEED: 24
SECOND_LABEL: 1
SAMPLE_RATE: 32000
MIN_FREQ: 20 #[20,50]
MAX_FREQ: 16000 #[14000,16000]
N_FFT: 2048 #[1024, 2048]
#################################################


#-------Spectogram Transform-------#
WIN_SIZE: 412
WIN_LAP: 100
#################################################


#-------Mel Spectogram Transform-------
N_MEL: 128
HOP_LENGTH: 512
NORMALIZED: True
CENTER: True
PAD_MODE: "constant"
NORM: "slaney"
MEL_SCALE: "slaney"
#################################################

#-------Audio Augmentation-------#
VolumeGain: False
AddShortNoises: False
AddGaussianNoise: False
TimeStretch: False
AddColorNoise: False
AddBackgroundNoise: False
#################################################

#-------Spectogram Augmentation-------#
XYMasking: True
CoarseDropout: False
HorizontalFlip: True
MixUp: False
CutMix: False
#################################################


#-------Training hyperparameter-------#
BACKBONE: "eca_nfnet_l0" # ["tf_efficientnet_b0.in1k" 256; "tf_efficientnetv2_s.in21k" 300;  "seresnext26t_32x4d.bt_in1k" 224; "tf_efficientnet_b3.ns_jft_in1k" 300; "resnet34.a1_in1k" 224; "efficientnet_b3.ra2_in1k" 288; "resnet50.a1_in1k" 224; "eca_nfnet_l0.ra2_in1k" 224]
EPOCHS: 10 #[5,30]
FOLD: 5
BACTHSIZE: 48
LABEL_SMOOTHING: 0.
LOSS: CrossEntropyLoss #CrossEntropyLoss
#################################################